# Kotlin & JVM
kotlin.code.style=official
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
kotlin.native.ignoreDisabledTargets=true

# Gradle Performance Optimizations
org.gradle.caching=true
org.gradle.parallel=true

# ==============================================================================
# 📦 Core Contract Versioning
# ==============================================================================
core.version=1.0.2
core.apiLevel=4
core.protocolVersion=2.0


