org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
kotlin.native.ignoreDisabledTargets=true

# ==============================================================================
# 📦 Core Contract Versioning
# ==============================================================================
core.version=1.0.2
core.apiLevel=4
core.protocolVersion=2.0

